### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by zeacot** [gamemann/XDP-Forwarding#3]
How to compile?

**Comment by sheharyaar** [comment]
As mentioned in the README :

You will need `make`, `clang`, `libelf`, and `llvm` since we use these packages to build the project. Additionally, you will also need `libconfig` (`libconfig-dev` is the package on Ubuntu/Debian systems) for parsing the config file.

For Ubuntu/Debian, the following should work.
`apt install build-essential make clang libelf-dev llvm libconfig-dev`
If you have another distro then install the equivalent packages in your distro.

To compile :
run `make` or `make all` and it should be fine

**Comment by gamemann** [comment]
Hey! I'm sorry for the late reply, I've been really busy recently.

I'm going to close this issue for now, but if you have any more questions, please let me know!

Also, thank you Sheharyaar for helping!
