### ISSUE TITLE
Error while adding rules

### ISSUE THREAD

**Issue by zeacot** [gamemann/XDP-Forwarding#6]
I compiled the tool & mounted the bpf file system. Now whenever I try to add rules it given me an error saying "Could not retrieve the forward map. Exciting..."

Can someone please tell me how can I fix this?
As writted in the readme, xdp program pins tho bpf maps to /sys/fs/bpf/xdpfwd. I did ls /sys/fs/bpf/ and the directory was empty.

**Comment by gamemann** [comment]
Hey! I'm sorry for the late reply. I've been really busy with some other projects.

Are you still having issues and if so, what Linux distro + kernel are you running? You can find the Linux distro via `cat /etc/*-release` and the kernel via `uname -r`. 

Thank you!

**Comment by soreana** [comment]
@gamemann I've got the same error. I'm using the Debian 11 with the following kernel. Can you help me, please?
```
root@front:~/desktop/XDP-Forwarding# uname -r
5.10.0-18-amd64
```

**Comment by soreana** [comment]
Got the same error on Ubuntu 20.04.

```
root@front:~/desktop/XDP-Forwarding# uname -r
5.4.0-128-generic
```

**Comment by gamemann** [comment]
@soreana Hey, I'm sorry for the late reply, I've been super busy 😭

I tested the program on a newer Ubuntu VM and didn't have any issues. Is the `xdpfwd` program running while you're trying to add these forwarding rules? If not, the program must be running since the maps are only available on the file system when the XDP program is running.

I made a [YouTube video](https://www.youtube.com/watch?v=x1Z4bcnLo14) demonstrating what I did on my newer Ubuntu VM which hadn't ran the software before.

## Server & VM Information
* Running Ubuntu 20.04 and kernel `5.4.0-131-generic`.
* AMD Ryzen 5 3600X @ 3.8 GHz.
* 32 GBs of DDR4 RAM.
* 1 TB SSD.

Information from `/etc/*-release` file.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
